// Code generated by hertz generator.

package job

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _jobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deleteMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletejobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryjobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createjobMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatejobstatusMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _fileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _attrsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryjoboutputattrMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _downloadjoboutputMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _attestationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryjobattestationreportMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _outputMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitjobMw() []app.HandlerFunc {
	// your code...
	return nil
}
