// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"

	"github.com/tiktok-privacy-innovation/PrivacyGo-DataCleanRoom/app/dcr_api/biz/dal"
	"github.com/tiktok-privacy-innovation/PrivacyGo-DataCleanRoom/pkg/config"
)

func Init() {
	err := config.InitConfig()
	if err != nil {
		hlog.Errorf("failed to init config %+v", err)
		panic(err)
	}
	dal.Init()
}

func main() {
	Init()
	h := server.Default(server.WithHostPorts(":8080"))

	register(h)
	h.Spin()
}
